name: museum_guide_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
  flutter_local_notifications: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  http: ^0.12.0+2
  intl: 0.15.8


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - ./config.json
   # License https://unsplash.com/photos/FFBkz2lOTkE FREE COMMERCIAL USE
   - images/exhibitions-list-cover.jpg

   # License https://unsplash.com/photos/kJFzlWhFlnE FREE COMMERCIAL USE
   - images/exhibition-card-missing-cover.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300          
        - asset: fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
